name:           Bootstrap Blog
description:    Official blog for the Bootstrap framework.
url:            http://blog.getbootstrap.com

markdown:       rdiscount
highlighter:    true
permalink:      pretty
paginate:       5
encoding:       UTF-8
baseurl:        /

exclude:        ["README.md"]
